preset = ""

[canvas]
width = 384
height = 192

[margins]
left = 8
right = 8
top = 26
bottom = 10

[background_image]
bg_image_is_set = false
background_image = "casioplot/calculator"

[show_screen]
show_screen = true

[saving_screen]
save_screen = false
filename = "casioplot"
image_format = "png"
save_multiple = false
save_rate = 0
