preset = ""

[canvas]
width = 384
height = 192

[margins]
left = 0
right = 0
top = 0
bottom = 0

[background_image]
bg_image_is_set = false
background_image = "casioplot/blanck"

[show_screen]
show_screen = true

[saving_screen]
save_screen = false
filename = "casioplot"
image_format = "png"
save_multiple = false
save_rate = 0
