[canvas]
width = 384
height = 192

[margins]
left_margin = 0
right_margin = 0
top_margin = 0
bottom_margin = 0

[background]
bg_image_is_set = false
background_image = "bg_images/blanck"

[show_screen]
show_screen = true

[saving_screen]
save_screen = false
filename = "casioplot"
image_format = "png"
save_multiple = false
save_rate = 0
